server:
  port: 8090
  servlet:
    contextPath: /HypoTravelSystem
# Actuator https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers
  endpoint:
    health:
      show-components: always
      show-details: always
      group:
        oep:
          include: googleDownstream
  health:
    oep:
      enabled: true
    mail:
      enabled: false

toggle:
  features:
    cache:
      enabled: true
    swagger:
      enabled: true
      desc: "API docs: http://localhost:8090/{context-path}/swagger-ui/index.html"